/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include <graphicsview.h>
#include <treeview.h>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *createProject;
    QAction *openProject;
    QAction *closeProject;
    QAction *Revocation;
    QAction *Restore;
    QAction *table_of_Contents;
    QAction *Index;
    QAction *Online_Help;
    QAction *Pick_up;
    QAction *Drag;
    QAction *extend;
    QAction *merge;
    QAction *delete_2;
    QAction *copy;
    QAction *Cutting;
    QAction *Property_superposition;
    QAction *Unselected;
    QAction *saveProjectAs;
    QAction *saveProject;
    QAction *reduction;
    QAction *whirl_alone;
    QAction *whirl;
    QAction *panoramic;
    QAction *Plan_view;
    QAction *Bottom_view;
    QAction *Parallel_projection;
    QAction *Perspective_projection;
    QAction *enlarge;
    QAction *Narrow;
    QAction *Outsourcing_box;
    QAction *XYZ;
    QAction *Staff;
    QAction *North_view;
    QAction *Wellhead;
    QAction *Well_trajectory;
    QAction *Logs;
    QAction *Perforation;
    QAction *Stratified;
    QAction *Reservoir_Simulation;
    QAction *Geological_model;
    QAction *crack;
    QAction *color;
    QAction *Hide_Show;
    QAction *move;
    QAction *Light_control;
    QAction *drilling;
    QAction *profile;
    QAction *well_deviation;
    QAction *straight_line;
    QAction *text_editor;
    QAction *Draw_boundary;
    QAction *Generate_contours;
    QAction *layer;
    QAction *Structural_map;
    QAction *Thematic_map;
    QAction *point;
    QAction *line;
    QAction *surface;
    QAction *body_part;
    QAction *Sphere;
    QAction *cuboid;
    QAction *Ellipsoid;
    QAction *Cone;
    QAction *Cylinder;
    QAction *Yuantong;
    QAction *Ring;
    QAction *AssistantView;
    QAction *loadStrataSurface;
    QAction *loadFault;
    QAction *loadWell;
    QAction *loadSModel;
    QAction *loadVModel;
    QAction *loadExplorationResult;
    QAction *loadProfile;
    QAction *loadCompositeColumn;
    QAction *saveProjectAS;
    QAction *quit;
    QAction *ExplorationResultDataTransForm;
    QAction *ProfileDataTransform;
    QAction *SinglewellDataTransform;
    QAction *DataTransform;
    QWidget *centralWidget;
    QHBoxLayout *horizontalLayout_2;
    QHBoxLayout *horizontalLayout;
    TreeView *treeView;
    QVBoxLayout *verticalLayout_3;
    GraphicsView *graphicsView;
    QGraphicsView *graphicsView_Bottom;
    QVBoxLayout *verticalLayout_6;
    QGraphicsView *graphicsView_RTop;
    QGraphicsView *graphicsView_RBottom;
    QMenuBar *menuBar;
    QMenu *menu_2;
    QMenu *menu_5;
    QMenu *menu_10;
    QMenu *menu_3;
    QMenu *menu_6;
    QMenu *menu_7;
    QMenu *menu_4;
    QMenu *menu_T;
    QMenu *menu_R;
    QMenu *menu_D;
    QMenu *menu_8;
    QMenu *menu_11;
    QMenu *menu;
    QMenu *menu_12;
    QMenu *menu_P;
    QStatusBar *statusBar;
    QToolBar *mainToolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(889, 574);
        createProject = new QAction(MainWindow);
        createProject->setObjectName(QStringLiteral("createProject"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/File/images/new.png"), QSize(), QIcon::Normal, QIcon::Off);
        createProject->setIcon(icon);
        openProject = new QAction(MainWindow);
        openProject->setObjectName(QStringLiteral("openProject"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/File/images/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        openProject->setIcon(icon1);
        closeProject = new QAction(MainWindow);
        closeProject->setObjectName(QStringLiteral("closeProject"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/File/images/exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        closeProject->setIcon(icon2);
        Revocation = new QAction(MainWindow);
        Revocation->setObjectName(QStringLiteral("Revocation"));
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/File/images/further.png"), QSize(), QIcon::Normal, QIcon::Off);
        Revocation->setIcon(icon3);
        Restore = new QAction(MainWindow);
        Restore->setObjectName(QStringLiteral("Restore"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/File/images/Revocation.png"), QSize(), QIcon::Normal, QIcon::Off);
        Restore->setIcon(icon4);
        table_of_Contents = new QAction(MainWindow);
        table_of_Contents->setObjectName(QStringLiteral("table_of_Contents"));
        QIcon icon5;
        icon5.addFile(QStringLiteral(":/File/images/table of Contents.png"), QSize(), QIcon::Normal, QIcon::Off);
        table_of_Contents->setIcon(icon5);
        Index = new QAction(MainWindow);
        Index->setObjectName(QStringLiteral("Index"));
        QIcon icon6;
        icon6.addFile(QStringLiteral(":/File/images/index.png"), QSize(), QIcon::Normal, QIcon::Off);
        Index->setIcon(icon6);
        Online_Help = new QAction(MainWindow);
        Online_Help->setObjectName(QStringLiteral("Online_Help"));
        QIcon icon7;
        icon7.addFile(QStringLiteral(":/File/images/Online Help.png"), QSize(), QIcon::Normal, QIcon::Off);
        Online_Help->setIcon(icon7);
        Pick_up = new QAction(MainWindow);
        Pick_up->setObjectName(QStringLiteral("Pick_up"));
        QIcon icon8;
        icon8.addFile(QStringLiteral(":/File/images/Pick up.png"), QSize(), QIcon::Normal, QIcon::Off);
        Pick_up->setIcon(icon8);
        Drag = new QAction(MainWindow);
        Drag->setObjectName(QStringLiteral("Drag"));
        QIcon icon9;
        icon9.addFile(QStringLiteral(":/File/images/Drag.png"), QSize(), QIcon::Normal, QIcon::Off);
        Drag->setIcon(icon9);
        extend = new QAction(MainWindow);
        extend->setObjectName(QStringLiteral("extend"));
        QIcon icon10;
        icon10.addFile(QStringLiteral(":/File/images/extend.png"), QSize(), QIcon::Normal, QIcon::Off);
        extend->setIcon(icon10);
        merge = new QAction(MainWindow);
        merge->setObjectName(QStringLiteral("merge"));
        QIcon icon11;
        icon11.addFile(QStringLiteral(":/File/images/merge.png"), QSize(), QIcon::Normal, QIcon::Off);
        merge->setIcon(icon11);
        delete_2 = new QAction(MainWindow);
        delete_2->setObjectName(QStringLiteral("delete_2"));
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/File/images/delete.png"), QSize(), QIcon::Normal, QIcon::Off);
        delete_2->setIcon(icon12);
        copy = new QAction(MainWindow);
        copy->setObjectName(QStringLiteral("copy"));
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/File/images/copy.png"), QSize(), QIcon::Normal, QIcon::Off);
        copy->setIcon(icon13);
        Cutting = new QAction(MainWindow);
        Cutting->setObjectName(QStringLiteral("Cutting"));
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/File/images/Cutting.png"), QSize(), QIcon::Normal, QIcon::Off);
        Cutting->setIcon(icon14);
        Property_superposition = new QAction(MainWindow);
        Property_superposition->setObjectName(QStringLiteral("Property_superposition"));
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/File/images/Property superposition.png"), QSize(), QIcon::Normal, QIcon::Off);
        Property_superposition->setIcon(icon15);
        Unselected = new QAction(MainWindow);
        Unselected->setObjectName(QStringLiteral("Unselected"));
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/File/images/Unselected.png"), QSize(), QIcon::Normal, QIcon::Off);
        Unselected->setIcon(icon16);
        saveProjectAs = new QAction(MainWindow);
        saveProjectAs->setObjectName(QStringLiteral("saveProjectAs"));
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/File/images/Save as.png"), QSize(), QIcon::Normal, QIcon::Off);
        saveProjectAs->setIcon(icon17);
        saveProject = new QAction(MainWindow);
        saveProject->setObjectName(QStringLiteral("saveProject"));
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/File/images/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        saveProject->setIcon(icon18);
        reduction = new QAction(MainWindow);
        reduction->setObjectName(QStringLiteral("reduction"));
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/File/images/reduction.png"), QSize(), QIcon::Normal, QIcon::Off);
        reduction->setIcon(icon19);
        whirl_alone = new QAction(MainWindow);
        whirl_alone->setObjectName(QStringLiteral("whirl_alone"));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/File/images/whirl\357\274\210alone\357\274\211.png"), QSize(), QIcon::Normal, QIcon::Off);
        whirl_alone->setIcon(icon20);
        whirl = new QAction(MainWindow);
        whirl->setObjectName(QStringLiteral("whirl"));
        QIcon icon21;
        icon21.addFile(QStringLiteral(":/File/images/whirl.png"), QSize(), QIcon::Normal, QIcon::Off);
        whirl->setIcon(icon21);
        panoramic = new QAction(MainWindow);
        panoramic->setObjectName(QStringLiteral("panoramic"));
        QIcon icon22;
        icon22.addFile(QStringLiteral(":/File/images/panoramic.png"), QSize(), QIcon::Normal, QIcon::Off);
        panoramic->setIcon(icon22);
        Plan_view = new QAction(MainWindow);
        Plan_view->setObjectName(QStringLiteral("Plan_view"));
        QIcon icon23;
        icon23.addFile(QStringLiteral(":/File/images/Plan view.png"), QSize(), QIcon::Normal, QIcon::Off);
        Plan_view->setIcon(icon23);
        Bottom_view = new QAction(MainWindow);
        Bottom_view->setObjectName(QStringLiteral("Bottom_view"));
        QIcon icon24;
        icon24.addFile(QStringLiteral(":/File/images/Bottom view.png"), QSize(), QIcon::Normal, QIcon::Off);
        Bottom_view->setIcon(icon24);
        Parallel_projection = new QAction(MainWindow);
        Parallel_projection->setObjectName(QStringLiteral("Parallel_projection"));
        QIcon icon25;
        icon25.addFile(QStringLiteral(":/File/images/Parallel projection.png"), QSize(), QIcon::Normal, QIcon::Off);
        Parallel_projection->setIcon(icon25);
        Perspective_projection = new QAction(MainWindow);
        Perspective_projection->setObjectName(QStringLiteral("Perspective_projection"));
        QIcon icon26;
        icon26.addFile(QStringLiteral(":/File/images/Perspective projection.png"), QSize(), QIcon::Normal, QIcon::Off);
        Perspective_projection->setIcon(icon26);
        enlarge = new QAction(MainWindow);
        enlarge->setObjectName(QStringLiteral("enlarge"));
        QIcon icon27;
        icon27.addFile(QStringLiteral(":/File/images/enlarge.png"), QSize(), QIcon::Normal, QIcon::Off);
        enlarge->setIcon(icon27);
        Narrow = new QAction(MainWindow);
        Narrow->setObjectName(QStringLiteral("Narrow"));
        QIcon icon28;
        icon28.addFile(QStringLiteral(":/File/images/Narrow.png"), QSize(), QIcon::Normal, QIcon::Off);
        Narrow->setIcon(icon28);
        Outsourcing_box = new QAction(MainWindow);
        Outsourcing_box->setObjectName(QStringLiteral("Outsourcing_box"));
        QIcon icon29;
        icon29.addFile(QStringLiteral(":/File/images/Outsourcing box.png"), QSize(), QIcon::Normal, QIcon::Off);
        Outsourcing_box->setIcon(icon29);
        XYZ = new QAction(MainWindow);
        XYZ->setObjectName(QStringLiteral("XYZ"));
        QIcon icon30;
        icon30.addFile(QStringLiteral(":/File/images/XYZ.png"), QSize(), QIcon::Normal, QIcon::Off);
        XYZ->setIcon(icon30);
        Staff = new QAction(MainWindow);
        Staff->setObjectName(QStringLiteral("Staff"));
        QIcon icon31;
        icon31.addFile(QStringLiteral(":/File/images/Staff.png"), QSize(), QIcon::Normal, QIcon::Off);
        Staff->setIcon(icon31);
        North_view = new QAction(MainWindow);
        North_view->setObjectName(QStringLiteral("North_view"));
        QIcon icon32;
        icon32.addFile(QStringLiteral(":/File/images/North view.png"), QSize(), QIcon::Normal, QIcon::Off);
        North_view->setIcon(icon32);
        Wellhead = new QAction(MainWindow);
        Wellhead->setObjectName(QStringLiteral("Wellhead"));
        QIcon icon33;
        icon33.addFile(QStringLiteral(":/File/images/Wellhead.png"), QSize(), QIcon::Normal, QIcon::Off);
        Wellhead->setIcon(icon33);
        Well_trajectory = new QAction(MainWindow);
        Well_trajectory->setObjectName(QStringLiteral("Well_trajectory"));
        QIcon icon34;
        icon34.addFile(QStringLiteral(":/File/images/Well trajectory.png"), QSize(), QIcon::Normal, QIcon::Off);
        Well_trajectory->setIcon(icon34);
        Logs = new QAction(MainWindow);
        Logs->setObjectName(QStringLiteral("Logs"));
        QIcon icon35;
        icon35.addFile(QStringLiteral(":/File/images/Logs.png"), QSize(), QIcon::Normal, QIcon::Off);
        Logs->setIcon(icon35);
        Perforation = new QAction(MainWindow);
        Perforation->setObjectName(QStringLiteral("Perforation"));
        QIcon icon36;
        icon36.addFile(QStringLiteral(":/File/images/Perforation.png"), QSize(), QIcon::Normal, QIcon::Off);
        Perforation->setIcon(icon36);
        Stratified = new QAction(MainWindow);
        Stratified->setObjectName(QStringLiteral("Stratified"));
        QIcon icon37;
        icon37.addFile(QStringLiteral(":/File/images/Stratified.png"), QSize(), QIcon::Normal, QIcon::Off);
        Stratified->setIcon(icon37);
        Reservoir_Simulation = new QAction(MainWindow);
        Reservoir_Simulation->setObjectName(QStringLiteral("Reservoir_Simulation"));
        QIcon icon38;
        icon38.addFile(QStringLiteral(":/File/images/Reservoir Simulation.png"), QSize(), QIcon::Normal, QIcon::Off);
        Reservoir_Simulation->setIcon(icon38);
        Geological_model = new QAction(MainWindow);
        Geological_model->setObjectName(QStringLiteral("Geological_model"));
        QIcon icon39;
        icon39.addFile(QStringLiteral(":/File/images/Geological model.png"), QSize(), QIcon::Normal, QIcon::Off);
        Geological_model->setIcon(icon39);
        crack = new QAction(MainWindow);
        crack->setObjectName(QStringLiteral("crack"));
        QIcon icon40;
        icon40.addFile(QStringLiteral(":/File/images/crack.png"), QSize(), QIcon::Normal, QIcon::Off);
        crack->setIcon(icon40);
        color = new QAction(MainWindow);
        color->setObjectName(QStringLiteral("color"));
        QIcon icon41;
        icon41.addFile(QStringLiteral(":/File/images/color.png"), QSize(), QIcon::Normal, QIcon::Off);
        color->setIcon(icon41);
        Hide_Show = new QAction(MainWindow);
        Hide_Show->setObjectName(QStringLiteral("Hide_Show"));
        QIcon icon42;
        icon42.addFile(QStringLiteral(":/File/images/Hide Show.png"), QSize(), QIcon::Normal, QIcon::Off);
        Hide_Show->setIcon(icon42);
        move = new QAction(MainWindow);
        move->setObjectName(QStringLiteral("move"));
        QIcon icon43;
        icon43.addFile(QStringLiteral(":/File/images/move.png"), QSize(), QIcon::Normal, QIcon::Off);
        move->setIcon(icon43);
        Light_control = new QAction(MainWindow);
        Light_control->setObjectName(QStringLiteral("Light_control"));
        QIcon icon44;
        icon44.addFile(QStringLiteral(":/File/images/Light control.png"), QSize(), QIcon::Normal, QIcon::Off);
        Light_control->setIcon(icon44);
        drilling = new QAction(MainWindow);
        drilling->setObjectName(QStringLiteral("drilling"));
        QIcon icon45;
        icon45.addFile(QStringLiteral(":/File/images/drilling.png"), QSize(), QIcon::Normal, QIcon::Off);
        drilling->setIcon(icon45);
        profile = new QAction(MainWindow);
        profile->setObjectName(QStringLiteral("profile"));
        QIcon icon46;
        icon46.addFile(QStringLiteral(":/File/images/profile.png"), QSize(), QIcon::Normal, QIcon::Off);
        profile->setIcon(icon46);
        well_deviation = new QAction(MainWindow);
        well_deviation->setObjectName(QStringLiteral("well_deviation"));
        QIcon icon47;
        icon47.addFile(QStringLiteral(":/File/images/well deviation.png"), QSize(), QIcon::Normal, QIcon::Off);
        well_deviation->setIcon(icon47);
        straight_line = new QAction(MainWindow);
        straight_line->setObjectName(QStringLiteral("straight_line"));
        QIcon icon48;
        icon48.addFile(QStringLiteral(":/File/images/straight line.png"), QSize(), QIcon::Normal, QIcon::Off);
        straight_line->setIcon(icon48);
        text_editor = new QAction(MainWindow);
        text_editor->setObjectName(QStringLiteral("text_editor"));
        QIcon icon49;
        icon49.addFile(QStringLiteral(":/File/images/text editor.png"), QSize(), QIcon::Normal, QIcon::Off);
        text_editor->setIcon(icon49);
        Draw_boundary = new QAction(MainWindow);
        Draw_boundary->setObjectName(QStringLiteral("Draw_boundary"));
        QIcon icon50;
        icon50.addFile(QStringLiteral(":/File/images/Draw boundary.png"), QSize(), QIcon::Normal, QIcon::Off);
        Draw_boundary->setIcon(icon50);
        Generate_contours = new QAction(MainWindow);
        Generate_contours->setObjectName(QStringLiteral("Generate_contours"));
        QIcon icon51;
        icon51.addFile(QStringLiteral(":/File/images/Generate contours.png"), QSize(), QIcon::Normal, QIcon::Off);
        Generate_contours->setIcon(icon51);
        layer = new QAction(MainWindow);
        layer->setObjectName(QStringLiteral("layer"));
        QIcon icon52;
        icon52.addFile(QStringLiteral(":/File/images/layer.png"), QSize(), QIcon::Normal, QIcon::Off);
        layer->setIcon(icon52);
        Structural_map = new QAction(MainWindow);
        Structural_map->setObjectName(QStringLiteral("Structural_map"));
        QIcon icon53;
        icon53.addFile(QStringLiteral(":/File/images/Structural map.png"), QSize(), QIcon::Normal, QIcon::Off);
        Structural_map->setIcon(icon53);
        Thematic_map = new QAction(MainWindow);
        Thematic_map->setObjectName(QStringLiteral("Thematic_map"));
        QIcon icon54;
        icon54.addFile(QStringLiteral(":/File/images/Thematic map.png"), QSize(), QIcon::Normal, QIcon::Off);
        Thematic_map->setIcon(icon54);
        point = new QAction(MainWindow);
        point->setObjectName(QStringLiteral("point"));
        QIcon icon55;
        icon55.addFile(QStringLiteral(":/File/images/point.png"), QSize(), QIcon::Normal, QIcon::Off);
        point->setIcon(icon55);
        line = new QAction(MainWindow);
        line->setObjectName(QStringLiteral("line"));
        QIcon icon56;
        icon56.addFile(QStringLiteral(":/File/images/line.png"), QSize(), QIcon::Normal, QIcon::Off);
        line->setIcon(icon56);
        surface = new QAction(MainWindow);
        surface->setObjectName(QStringLiteral("surface"));
        QIcon icon57;
        icon57.addFile(QStringLiteral(":/File/images/surface.png"), QSize(), QIcon::Normal, QIcon::Off);
        surface->setIcon(icon57);
        body_part = new QAction(MainWindow);
        body_part->setObjectName(QStringLiteral("body_part"));
        QIcon icon58;
        icon58.addFile(QStringLiteral(":/File/images/body part.png"), QSize(), QIcon::Normal, QIcon::Off);
        body_part->setIcon(icon58);
        Sphere = new QAction(MainWindow);
        Sphere->setObjectName(QStringLiteral("Sphere"));
        QIcon icon59;
        icon59.addFile(QStringLiteral(":/File/images/Sphere.png"), QSize(), QIcon::Normal, QIcon::Off);
        Sphere->setIcon(icon59);
        cuboid = new QAction(MainWindow);
        cuboid->setObjectName(QStringLiteral("cuboid"));
        QIcon icon60;
        icon60.addFile(QStringLiteral(":/File/images/cuboid.png"), QSize(), QIcon::Normal, QIcon::Off);
        cuboid->setIcon(icon60);
        Ellipsoid = new QAction(MainWindow);
        Ellipsoid->setObjectName(QStringLiteral("Ellipsoid"));
        QIcon icon61;
        icon61.addFile(QStringLiteral(":/File/images/Ellipsoid.png"), QSize(), QIcon::Normal, QIcon::Off);
        Ellipsoid->setIcon(icon61);
        Cone = new QAction(MainWindow);
        Cone->setObjectName(QStringLiteral("Cone"));
        QIcon icon62;
        icon62.addFile(QStringLiteral(":/File/images/Cone.png"), QSize(), QIcon::Normal, QIcon::Off);
        Cone->setIcon(icon62);
        Cylinder = new QAction(MainWindow);
        Cylinder->setObjectName(QStringLiteral("Cylinder"));
        QIcon icon63;
        icon63.addFile(QStringLiteral(":/File/images/Cylinder.png"), QSize(), QIcon::Normal, QIcon::Off);
        Cylinder->setIcon(icon63);
        Yuantong = new QAction(MainWindow);
        Yuantong->setObjectName(QStringLiteral("Yuantong"));
        QIcon icon64;
        icon64.addFile(QStringLiteral(":/File/images/Yuantong.png"), QSize(), QIcon::Normal, QIcon::Off);
        Yuantong->setIcon(icon64);
        Ring = new QAction(MainWindow);
        Ring->setObjectName(QStringLiteral("Ring"));
        QIcon icon65;
        icon65.addFile(QStringLiteral(":/File/images/Ring.png"), QSize(), QIcon::Normal, QIcon::Off);
        Ring->setIcon(icon65);
        AssistantView = new QAction(MainWindow);
        AssistantView->setObjectName(QStringLiteral("AssistantView"));
        loadStrataSurface = new QAction(MainWindow);
        loadStrataSurface->setObjectName(QStringLiteral("loadStrataSurface"));
        loadFault = new QAction(MainWindow);
        loadFault->setObjectName(QStringLiteral("loadFault"));
        loadWell = new QAction(MainWindow);
        loadWell->setObjectName(QStringLiteral("loadWell"));
        loadSModel = new QAction(MainWindow);
        loadSModel->setObjectName(QStringLiteral("loadSModel"));
        loadVModel = new QAction(MainWindow);
        loadVModel->setObjectName(QStringLiteral("loadVModel"));
        loadExplorationResult = new QAction(MainWindow);
        loadExplorationResult->setObjectName(QStringLiteral("loadExplorationResult"));
        loadProfile = new QAction(MainWindow);
        loadProfile->setObjectName(QStringLiteral("loadProfile"));
        loadCompositeColumn = new QAction(MainWindow);
        loadCompositeColumn->setObjectName(QStringLiteral("loadCompositeColumn"));
        saveProjectAS = new QAction(MainWindow);
        saveProjectAS->setObjectName(QStringLiteral("saveProjectAS"));
        quit = new QAction(MainWindow);
        quit->setObjectName(QStringLiteral("quit"));
        ExplorationResultDataTransForm = new QAction(MainWindow);
        ExplorationResultDataTransForm->setObjectName(QStringLiteral("ExplorationResultDataTransForm"));
        ProfileDataTransform = new QAction(MainWindow);
        ProfileDataTransform->setObjectName(QStringLiteral("ProfileDataTransform"));
        SinglewellDataTransform = new QAction(MainWindow);
        SinglewellDataTransform->setObjectName(QStringLiteral("SinglewellDataTransform"));
        DataTransform = new QAction(MainWindow);
        DataTransform->setObjectName(QStringLiteral("DataTransform"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        horizontalLayout_2 = new QHBoxLayout(centralWidget);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QStringLiteral("horizontalLayout_2"));
        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(6);
        horizontalLayout->setObjectName(QStringLiteral("horizontalLayout"));
        treeView = new TreeView(centralWidget);
        treeView->setObjectName(QStringLiteral("treeView"));
        QSizePolicy sizePolicy(QSizePolicy::MinimumExpanding, QSizePolicy::MinimumExpanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(treeView->sizePolicy().hasHeightForWidth());
        treeView->setSizePolicy(sizePolicy);
        treeView->setMinimumSize(QSize(170, 0));
        treeView->setMaximumSize(QSize(170, 16777215));
        treeView->setContextMenuPolicy(Qt::CustomContextMenu);
        treeView->setAutoFillBackground(true);
        treeView->setVerticalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        treeView->setHorizontalScrollBarPolicy(Qt::ScrollBarAsNeeded);
        treeView->setSizeAdjustPolicy(QAbstractScrollArea::AdjustToContents);
        treeView->setAutoScroll(true);
        treeView->setAutoScrollMargin(16);
        treeView->setAlternatingRowColors(true);
        treeView->setIconSize(QSize(16, 16));
        treeView->setAutoExpandDelay(-1);
        treeView->setUniformRowHeights(true);
        treeView->setAnimated(true);
        treeView->setHeaderHidden(true);
        treeView->header()->setVisible(false);
        treeView->header()->setCascadingSectionResizes(false);
        treeView->header()->setHighlightSections(false);
        treeView->header()->setProperty("showSortIndicator", QVariant(false));

        horizontalLayout->addWidget(treeView);

        verticalLayout_3 = new QVBoxLayout();
        verticalLayout_3->setSpacing(6);
        verticalLayout_3->setObjectName(QStringLiteral("verticalLayout_3"));
        graphicsView = new GraphicsView(centralWidget);
        graphicsView->setObjectName(QStringLiteral("graphicsView"));
        QSizePolicy sizePolicy1(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(graphicsView->sizePolicy().hasHeightForWidth());
        graphicsView->setSizePolicy(sizePolicy1);
        graphicsView->setContextMenuPolicy(Qt::CustomContextMenu);

        verticalLayout_3->addWidget(graphicsView);

        graphicsView_Bottom = new QGraphicsView(centralWidget);
        graphicsView_Bottom->setObjectName(QStringLiteral("graphicsView_Bottom"));
        QSizePolicy sizePolicy2(QSizePolicy::Expanding, QSizePolicy::Fixed);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(graphicsView_Bottom->sizePolicy().hasHeightForWidth());
        graphicsView_Bottom->setSizePolicy(sizePolicy2);
        graphicsView_Bottom->setMinimumSize(QSize(0, 100));
        graphicsView_Bottom->setMaximumSize(QSize(16777215, 100));

        verticalLayout_3->addWidget(graphicsView_Bottom);


        horizontalLayout->addLayout(verticalLayout_3);

        verticalLayout_6 = new QVBoxLayout();
        verticalLayout_6->setSpacing(6);
        verticalLayout_6->setObjectName(QStringLiteral("verticalLayout_6"));
        graphicsView_RTop = new QGraphicsView(centralWidget);
        graphicsView_RTop->setObjectName(QStringLiteral("graphicsView_RTop"));
        graphicsView_RTop->setEnabled(true);
        QSizePolicy sizePolicy3(QSizePolicy::Fixed, QSizePolicy::Expanding);
        sizePolicy3.setHorizontalStretch(0);
        sizePolicy3.setVerticalStretch(0);
        sizePolicy3.setHeightForWidth(graphicsView_RTop->sizePolicy().hasHeightForWidth());
        graphicsView_RTop->setSizePolicy(sizePolicy3);
        graphicsView_RTop->setMinimumSize(QSize(170, 0));
        graphicsView_RTop->setMaximumSize(QSize(170, 16777215));

        verticalLayout_6->addWidget(graphicsView_RTop);

        graphicsView_RBottom = new QGraphicsView(centralWidget);
        graphicsView_RBottom->setObjectName(QStringLiteral("graphicsView_RBottom"));
        graphicsView_RBottom->setEnabled(true);
        sizePolicy3.setHeightForWidth(graphicsView_RBottom->sizePolicy().hasHeightForWidth());
        graphicsView_RBottom->setSizePolicy(sizePolicy3);
        graphicsView_RBottom->setMinimumSize(QSize(170, 0));
        graphicsView_RBottom->setMaximumSize(QSize(170, 16777215));

        verticalLayout_6->addWidget(graphicsView_RBottom);


        horizontalLayout->addLayout(verticalLayout_6);


        horizontalLayout_2->addLayout(horizontalLayout);

        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setEnabled(true);
        menuBar->setGeometry(QRect(0, 0, 889, 23));
        menu_2 = new QMenu(menuBar);
        menu_2->setObjectName(QStringLiteral("menu_2"));
        menu_5 = new QMenu(menu_2);
        menu_5->setObjectName(QStringLiteral("menu_5"));
        menu_10 = new QMenu(menu_5);
        menu_10->setObjectName(QStringLiteral("menu_10"));
        menu_3 = new QMenu(menuBar);
        menu_3->setObjectName(QStringLiteral("menu_3"));
        menu_6 = new QMenu(menu_3);
        menu_6->setObjectName(QStringLiteral("menu_6"));
        menu_7 = new QMenu(menu_3);
        menu_7->setObjectName(QStringLiteral("menu_7"));
        menu_4 = new QMenu(menuBar);
        menu_4->setObjectName(QStringLiteral("menu_4"));
        menu_T = new QMenu(menuBar);
        menu_T->setObjectName(QStringLiteral("menu_T"));
        menu_R = new QMenu(menuBar);
        menu_R->setObjectName(QStringLiteral("menu_R"));
        menu_D = new QMenu(menuBar);
        menu_D->setObjectName(QStringLiteral("menu_D"));
        menu_8 = new QMenu(menu_D);
        menu_8->setObjectName(QStringLiteral("menu_8"));
        menu_11 = new QMenu(menuBar);
        menu_11->setObjectName(QStringLiteral("menu_11"));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        menu_12 = new QMenu(menuBar);
        menu_12->setObjectName(QStringLiteral("menu_12"));
        menu_P = new QMenu(menuBar);
        menu_P->setObjectName(QStringLiteral("menu_P"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setEnabled(true);
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);

        menuBar->addAction(menu->menuAction());
        menuBar->addAction(menu_12->menuAction());
        menuBar->addAction(menu_D->menuAction());
        menuBar->addAction(menu_2->menuAction());
        menuBar->addAction(menu_11->menuAction());
        menuBar->addAction(menu_3->menuAction());
        menuBar->addAction(menu_T->menuAction());
        menuBar->addAction(menu_R->menuAction());
        menuBar->addAction(menu_4->menuAction());
        menuBar->addAction(menu_P->menuAction());
        menu_2->addAction(Revocation);
        menu_2->addAction(Restore);
        menu_2->addAction(reduction);
        menu_2->addAction(menu_5->menuAction());
        menu_2->addAction(merge);
        menu_2->addAction(delete_2);
        menu_2->addAction(copy);
        menu_2->addAction(Cutting);
        menu_5->addAction(Pick_up);
        menu_5->addAction(Drag);
        menu_5->addAction(menu_10->menuAction());
        menu_5->addAction(extend);
        menu_5->addAction(Unselected);
        menu_10->addAction(whirl_alone);
        menu_10->addAction(whirl);
        menu_3->addAction(Property_superposition);
        menu_3->addAction(menu_6->menuAction());
        menu_3->addAction(menu_7->menuAction());
        menu_3->addAction(Outsourcing_box);
        menu_3->addAction(XYZ);
        menu_3->addAction(Staff);
        menu_3->addAction(color);
        menu_3->addAction(Hide_Show);
        menu_3->addAction(move);
        menu_3->addAction(Light_control);
        menu_6->addAction(panoramic);
        menu_6->addAction(Plan_view);
        menu_6->addAction(Bottom_view);
        menu_6->addAction(North_view);
        menu_6->addAction(Parallel_projection);
        menu_6->addAction(Perspective_projection);
        menu_7->addAction(enlarge);
        menu_7->addAction(Narrow);
        menu_4->addAction(table_of_Contents);
        menu_4->addAction(Index);
        menu_4->addAction(Online_Help);
        menu_T->addAction(straight_line);
        menu_T->addAction(text_editor);
        menu_T->addAction(Draw_boundary);
        menu_T->addAction(Generate_contours);
        menu_T->addAction(layer);
        menu_T->addAction(AssistantView);
        menu_D->addAction(menu_8->menuAction());
        menu_D->addAction(Reservoir_Simulation);
        menu_D->addAction(Geological_model);
        menu_D->addAction(crack);
        menu_D->addAction(drilling);
        menu_D->addAction(profile);
        menu_D->addAction(Structural_map);
        menu_D->addAction(Thematic_map);
        menu_D->addAction(point);
        menu_D->addAction(line);
        menu_D->addAction(surface);
        menu_D->addAction(body_part);
        menu_8->addAction(Wellhead);
        menu_8->addAction(well_deviation);
        menu_8->addAction(Well_trajectory);
        menu_8->addAction(Logs);
        menu_8->addAction(Perforation);
        menu_8->addAction(Stratified);
        menu_11->addAction(Sphere);
        menu_11->addAction(cuboid);
        menu_11->addAction(Ellipsoid);
        menu_11->addAction(Cone);
        menu_11->addAction(Cylinder);
        menu_11->addAction(Yuantong);
        menu_11->addAction(Ring);
        menu->addAction(createProject);
        menu->addAction(openProject);
        menu->addAction(saveProject);
        menu->addAction(saveProjectAS);
        menu->addAction(closeProject);
        menu->addSeparator();
        menu->addAction(quit);
        menu_12->addAction(loadStrataSurface);
        menu_12->addAction(loadFault);
        menu_12->addAction(loadWell);
        menu_12->addSeparator();
        menu_12->addAction(loadSModel);
        menu_12->addAction(loadVModel);
        menu_12->addSeparator();
        menu_12->addAction(loadExplorationResult);
        menu_12->addAction(loadProfile);
        menu_12->addAction(loadCompositeColumn);
        menu_P->addAction(ExplorationResultDataTransForm);
        menu_P->addAction(ProfileDataTransform);
        menu_P->addAction(SinglewellDataTransform);
        menu_P->addAction(DataTransform);
        mainToolBar->addAction(createProject);
        mainToolBar->addAction(openProject);
        mainToolBar->addAction(closeProject);
        mainToolBar->addSeparator();
        mainToolBar->addAction(Restore);
        mainToolBar->addAction(Revocation);
        mainToolBar->addAction(copy);
        mainToolBar->addAction(saveProject);
        mainToolBar->addAction(delete_2);
        mainToolBar->addAction(saveProjectAs);
        mainToolBar->addAction(enlarge);
        mainToolBar->addAction(Narrow);
        mainToolBar->addSeparator();
        mainToolBar->addAction(table_of_Contents);
        mainToolBar->addAction(Index);
        mainToolBar->addAction(Online_Help);
        mainToolBar->addSeparator();
        mainToolBar->addAction(Structural_map);
        mainToolBar->addAction(Thematic_map);
        mainToolBar->addAction(Wellhead);
        mainToolBar->addAction(Well_trajectory);
        mainToolBar->addAction(Logs);
        mainToolBar->addAction(Stratified);
        mainToolBar->addAction(Reservoir_Simulation);
        mainToolBar->addAction(Geological_model);
        mainToolBar->addAction(crack);
        mainToolBar->addAction(point);
        mainToolBar->addAction(line);
        mainToolBar->addAction(straight_line);
        mainToolBar->addAction(surface);
        mainToolBar->addAction(body_part);
        mainToolBar->addSeparator();
        mainToolBar->addAction(Sphere);
        mainToolBar->addAction(cuboid);
        mainToolBar->addAction(Ellipsoid);
        mainToolBar->addAction(Cone);
        mainToolBar->addAction(Cylinder);
        mainToolBar->addAction(Yuantong);
        mainToolBar->addAction(Ring);
        mainToolBar->addAction(text_editor);
        mainToolBar->addAction(Draw_boundary);
        mainToolBar->addAction(Generate_contours);
        mainToolBar->addAction(layer);
        mainToolBar->addAction(Pick_up);
        mainToolBar->addAction(Drag);
        mainToolBar->addAction(merge);
        mainToolBar->addAction(Property_superposition);
        mainToolBar->addAction(Cutting);
        mainToolBar->addAction(whirl);
        mainToolBar->addAction(whirl_alone);
        mainToolBar->addAction(Staff);
        mainToolBar->addAction(XYZ);
        mainToolBar->addAction(Outsourcing_box);
        mainToolBar->addAction(Unselected);
        mainToolBar->addAction(reduction);
        mainToolBar->addAction(extend);
        mainToolBar->addAction(panoramic);
        mainToolBar->addAction(North_view);
        mainToolBar->addAction(Plan_view);
        mainToolBar->addAction(Bottom_view);
        mainToolBar->addAction(Light_control);
        mainToolBar->addAction(drilling);
        mainToolBar->addAction(profile);
        mainToolBar->addAction(Parallel_projection);
        mainToolBar->addAction(Perspective_projection);
        mainToolBar->addAction(color);
        mainToolBar->addAction(Hide_Show);
        mainToolBar->addAction(move);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\346\262\271\350\227\217\346\225\260\346\215\256\344\270\211\347\273\264\345\217\257\350\247\206\345\214\226\345\271\263\345\217\260", 0));
        createProject->setText(QApplication::translate("MainWindow", "\346\226\260\345\273\272\345\267\245\347\250\213(N)", 0));
        createProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+N", 0));
        openProject->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200\345\267\245\347\250\213(O)", 0));
        openProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+O", 0));
        closeProject->setText(QApplication::translate("MainWindow", "\345\205\263\351\227\255\345\267\245\347\250\213(C)", 0));
        closeProject->setShortcut(QApplication::translate("MainWindow", "Ctrl+C", 0));
        Revocation->setText(QApplication::translate("MainWindow", "\345\211\215\350\277\233\344\270\200\346\255\245(W)", 0));
        Restore->setText(QApplication::translate("MainWindow", "\345\220\216\351\200\200\344\270\200\346\255\245(K)", 0));
        table_of_Contents->setText(QApplication::translate("MainWindow", "\347\233\256\345\275\225table of Contents", 0));
        Index->setText(QApplication::translate("MainWindow", "\347\264\242\345\274\225index", 0));
        Online_Help->setText(QApplication::translate("MainWindow", "\350\201\224\346\234\272\345\270\256\345\212\251Online Help", 0));
        Pick_up->setText(QApplication::translate("MainWindow", "\346\213\276\345\217\226", 0));
        Drag->setText(QApplication::translate("MainWindow", "\346\213\226\346\213\275", 0));
        extend->setText(QApplication::translate("MainWindow", "\345\273\266\345\261\225", 0));
        merge->setText(QApplication::translate("MainWindow", "\345\220\210\345\271\266", 0));
        delete_2->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244", 0));
        copy->setText(QApplication::translate("MainWindow", "\345\244\215\345\210\266", 0));
        Cutting->setText(QApplication::translate("MainWindow", "\345\210\207\345\211\262", 0));
        Property_superposition->setText(QApplication::translate("MainWindow", "\345\261\236\346\200\247\345\217\240\345\212\240", 0));
        Unselected->setText(QApplication::translate("MainWindow", "\345\217\215\351\200\211", 0));
        saveProjectAs->setText(QApplication::translate("MainWindow", "\345\267\245\347\250\213\345\217\246\345\255\230\344\270\272", 0));
        saveProject->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230\345\267\245\347\250\213(S)", 0));
        reduction->setText(QApplication::translate("MainWindow", "\350\277\230\345\216\237(O)", 0));
        whirl_alone->setText(QApplication::translate("MainWindow", "\346\227\213\350\275\254\347\211\251\344\275\223", 0));
        whirl->setText(QApplication::translate("MainWindow", "\346\227\213\350\275\254\345\234\272\346\231\257", 0));
        panoramic->setText(QApplication::translate("MainWindow", "\345\205\250\346\231\257", 0));
        Plan_view->setText(QApplication::translate("MainWindow", "\344\277\257\350\247\206\345\233\276", 0));
        Bottom_view->setText(QApplication::translate("MainWindow", "\344\273\260\350\247\206\345\233\276", 0));
        Parallel_projection->setText(QApplication::translate("MainWindow", "\345\271\263\350\241\214\346\212\225\345\275\261", 0));
        Perspective_projection->setText(QApplication::translate("MainWindow", "\351\200\217\350\247\206\346\212\225\345\275\261", 0));
        enlarge->setText(QApplication::translate("MainWindow", "\346\224\276\345\244\247", 0));
        Narrow->setText(QApplication::translate("MainWindow", "\347\274\251\345\260\217", 0));
        Outsourcing_box->setText(QApplication::translate("MainWindow", "\345\244\226\345\214\205\346\241\206", 0));
        XYZ->setText(QApplication::translate("MainWindow", "\345\235\220\346\240\207\350\275\264", 0));
        Staff->setText(QApplication::translate("MainWindow", "\346\240\207\345\260\272", 0));
        North_view->setText(QApplication::translate("MainWindow", "\346\255\243\345\214\227\350\247\206\345\233\276", 0));
        Wellhead->setText(QApplication::translate("MainWindow", "\344\272\225\345\244\264", 0));
        Well_trajectory->setText(QApplication::translate("MainWindow", "\344\272\225\350\275\250\350\277\271", 0));
        Logs->setText(QApplication::translate("MainWindow", "\346\265\213\344\272\225\346\233\262\347\272\277", 0));
        Perforation->setText(QApplication::translate("MainWindow", "\345\260\204\345\255\224", 0));
        Stratified->setText(QApplication::translate("MainWindow", "\345\210\206\345\261\202", 0));
        Reservoir_Simulation->setText(QApplication::translate("MainWindow", "\346\262\271\350\227\217\346\250\241\346\213\237", 0));
        Geological_model->setText(QApplication::translate("MainWindow", "\345\234\260\350\264\250\346\250\241\345\236\213", 0));
        crack->setText(QApplication::translate("MainWindow", "\350\243\202\347\274\235", 0));
        color->setText(QApplication::translate("MainWindow", "\350\203\214\346\231\257\350\211\262", 0));
        Hide_Show->setText(QApplication::translate("MainWindow", "\351\232\220\350\227\217\346\230\276\347\244\272", 0));
        move->setText(QApplication::translate("MainWindow", "\347\247\273\345\212\250", 0));
        Light_control->setText(QApplication::translate("MainWindow", "\345\205\211\346\272\220\346\216\247\345\210\266", 0));
        drilling->setText(QApplication::translate("MainWindow", "\351\222\273\345\255\224", 0));
        profile->setText(QApplication::translate("MainWindow", "\345\211\226\351\235\242", 0));
        well_deviation->setText(QApplication::translate("MainWindow", "\344\272\225\346\226\234", 0));
        straight_line->setText(QApplication::translate("MainWindow", "\347\224\273\347\272\277", 0));
        text_editor->setText(QApplication::translate("MainWindow", "\346\226\207\345\255\227\347\274\226\350\276\221", 0));
        Draw_boundary->setText(QApplication::translate("MainWindow", "\347\273\230\345\210\266\350\276\271\347\225\214", 0));
        Generate_contours->setText(QApplication::translate("MainWindow", "\347\224\237\346\210\220\347\255\211\345\200\274\347\272\277", 0));
        layer->setText(QApplication::translate("MainWindow", "\345\233\276\345\261\202\347\256\241\347\220\206", 0));
        Structural_map->setText(QApplication::translate("MainWindow", "\346\236\204\351\200\240\345\233\276", 0));
        Thematic_map->setText(QApplication::translate("MainWindow", "\344\270\223\351\242\230\345\233\276", 0));
        point->setText(QApplication::translate("MainWindow", "\347\202\271", 0));
        line->setText(QApplication::translate("MainWindow", "\347\272\277", 0));
        surface->setText(QApplication::translate("MainWindow", "\351\235\242", 0));
        body_part->setText(QApplication::translate("MainWindow", "\344\275\223", 0));
        Sphere->setText(QApplication::translate("MainWindow", "\347\220\203\344\275\223", 0));
        cuboid->setText(QApplication::translate("MainWindow", "\351\225\277\346\226\271\344\275\223", 0));
        Ellipsoid->setText(QApplication::translate("MainWindow", "\346\244\255\347\220\203\344\275\223", 0));
        Cone->setText(QApplication::translate("MainWindow", "\345\234\206\351\224\245\344\275\223", 0));
        Cylinder->setText(QApplication::translate("MainWindow", "\345\234\206\346\237\261\344\275\223", 0));
        Yuantong->setText(QApplication::translate("MainWindow", "\345\234\206\347\255\222", 0));
        Ring->setText(QApplication::translate("MainWindow", "\345\234\206\347\216\257", 0));
        AssistantView->setText(QApplication::translate("MainWindow", "\350\276\205\345\212\251\347\225\214\351\235\242", 0));
        loadStrataSurface->setText(QApplication::translate("MainWindow", "\345\234\260\345\261\202\351\235\242", 0));
#ifndef QT_NO_TOOLTIP
        loadStrataSurface->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\345\234\260\345\261\202\351\235\242\346\225\260\346\215\256", 0));
#endif // QT_NO_TOOLTIP
        loadFault->setText(QApplication::translate("MainWindow", "\346\226\255\345\261\202\351\235\242", 0));
#ifndef QT_NO_TOOLTIP
        loadFault->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\346\226\255\345\261\202\351\235\242\346\225\260\346\215\256", 0));
#endif // QT_NO_TOOLTIP
        loadWell->setText(QApplication::translate("MainWindow", "\344\272\225", 0));
#ifndef QT_NO_TOOLTIP
        loadWell->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\344\272\225\346\225\260\346\215\256", 0));
#endif // QT_NO_TOOLTIP
        loadSModel->setText(QApplication::translate("MainWindow", "\345\234\260\345\261\202\346\250\241\345\236\213\357\274\210\350\241\250\351\235\242\357\274\211", 0));
#ifndef QT_NO_TOOLTIP
        loadSModel->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\350\241\250\351\235\242\346\250\241\345\236\213\346\225\260\346\215\256", 0));
#endif // QT_NO_TOOLTIP
        loadVModel->setText(QApplication::translate("MainWindow", "\345\234\260\345\261\202\346\250\241\345\236\213\357\274\210\344\275\223\345\205\203\357\274\211", 0));
#ifndef QT_NO_TOOLTIP
        loadVModel->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\344\275\223\345\205\203\346\250\241\345\236\213\346\225\260\346\215\256", 0));
#endif // QT_NO_TOOLTIP
        loadExplorationResult->setText(QApplication::translate("MainWindow", "\345\213\230\346\216\242\346\210\220\346\236\234\345\233\276", 0));
#ifndef QT_NO_TOOLTIP
        loadExplorationResult->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\345\213\230\346\216\242\346\210\220\346\236\234\345\233\276", 0));
#endif // QT_NO_TOOLTIP
        loadProfile->setText(QApplication::translate("MainWindow", "\350\277\236\344\272\225\345\211\226\351\235\242\345\233\276", 0));
#ifndef QT_NO_TOOLTIP
        loadProfile->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\350\277\236\344\272\225\345\211\226\351\235\242\345\233\276", 0));
#endif // QT_NO_TOOLTIP
        loadCompositeColumn->setText(QApplication::translate("MainWindow", "\345\215\225\344\272\225\347\273\274\345\220\210\346\237\261\347\212\266\345\233\276", 0));
#ifndef QT_NO_TOOLTIP
        loadCompositeColumn->setToolTip(QApplication::translate("MainWindow", "\345\212\240\350\275\275\345\215\225\344\272\225\347\273\274\345\220\210\346\237\261\347\212\266\345\233\276", 0));
#endif // QT_NO_TOOLTIP
        saveProjectAS->setText(QApplication::translate("MainWindow", "\345\217\246\345\255\230\345\267\245\347\250\213", 0));
#ifndef QT_NO_TOOLTIP
        saveProjectAS->setToolTip(QApplication::translate("MainWindow", "\345\267\245\347\250\213\345\217\246\345\255\230\344\270\272...", 0));
#endif // QT_NO_TOOLTIP
        quit->setText(QApplication::translate("MainWindow", "\351\200\200\345\207\272", 0));
        ExplorationResultDataTransForm->setText(QApplication::translate("MainWindow", "\345\213\230\346\216\242\346\210\220\346\236\234\345\233\276\350\256\241\347\256\227", 0));
        ProfileDataTransform->setText(QApplication::translate("MainWindow", "\350\277\236\344\272\225\345\211\226\351\235\242\345\233\276\350\256\241\347\256\227", 0));
        SinglewellDataTransform->setText(QApplication::translate("MainWindow", "\347\273\274\345\220\210\346\237\261\347\212\266\345\233\276\350\256\241\347\256\227", 0));
        DataTransform->setText(QApplication::translate("MainWindow", "\346\225\260\346\215\256\346\240\241\346\255\243", 0));
        menu_2->setTitle(QApplication::translate("MainWindow", "\347\274\226\350\276\221(E)", 0));
        menu_5->setTitle(QApplication::translate("MainWindow", "\351\200\211\346\213\251", 0));
        menu_10->setTitle(QApplication::translate("MainWindow", "\346\227\213\350\275\254", 0));
        menu_3->setTitle(QApplication::translate("MainWindow", "\344\270\211\347\273\264\345\217\257\350\247\206\345\214\226(V)", 0));
        menu_6->setTitle(QApplication::translate("MainWindow", "\345\234\272\346\231\257\346\230\276\347\244\272", 0));
        menu_7->setTitle(QApplication::translate("MainWindow", "\347\274\251\346\224\276", 0));
        menu_4->setTitle(QApplication::translate("MainWindow", "\345\270\256\345\212\251(M)", 0));
        menu_T->setTitle(QApplication::translate("MainWindow", "\345\267\245\345\205\267\346\240\217(T)", 0));
        menu_R->setTitle(QApplication::translate("MainWindow", "\350\265\204\346\272\220(R)", 0));
        menu_D->setTitle(QApplication::translate("MainWindow", "\346\225\260\346\215\256(D)", 0));
        menu_8->setTitle(QApplication::translate("MainWindow", "\345\215\225\344\272\225", 0));
        menu_11->setTitle(QApplication::translate("MainWindow", "\345\237\272\346\234\254\345\207\240\344\275\225\344\275\223(G)", 0));
        menu->setTitle(QApplication::translate("MainWindow", "\346\226\207\344\273\266(F)", 0));
        menu_12->setTitle(QApplication::translate("MainWindow", "\345\212\240\350\275\275\346\225\260\346\215\256", 0));
        menu_P->setTitle(QApplication::translate("MainWindow", "\345\235\220\346\240\207\350\256\241\347\256\227(P)", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
